name: eoapi-workshop
channels:
  - conda-forge
dependencies:
  - jupyterlab
  - gdal=3.10
  - python=3.12
  - rust
  - pip
  - folium
  - geoalchemy2
  - geopandas
  - httpx
  - ipywidgets
  - pystac
  - pystac-client
  - rasterio
  - rio-stac
  - s3fs
  - shapely
  - pip:
    - pypgstac[psycopg]==0.9.6
    - stactools-sentinel2
variables:
  AWS_NO_SIGN_REQUEST: TRUE 
