name: fedgeoday25-workshop
channels:
  - conda-forge
dependencies:
  - gdal=3.10
  - python=3.12
  - rust
  - pip
  - folium
  - geoalchemy2
  - geopandas
  - httpx
  - pystac
  - pystac-client
  - pip:
    - pypgstac[psycopg]==0.9.6
