name: fedgeoday25-workshop
channels:
  - conda-forge
dependencies:
  - gdal=3.10
  - rust
  - python
  - pip
  - geoalchemy
  - geopandas
  - httpx
  - pystac
  - pystac-client
  - pip:
    - pypgstac[psycopg]==0.9.6
